@startuml

title __BUY2GETHER's Class Diagram__\n

    namespace com.pis.buy2gether {
     namespace usecases.home {
       namespace favoriteList {
         class com.pis.buy2gether.usecases.home.favoriteList.FavoriteFragment {
             + deleteFavorite()
             + onClick()
             + onCreateView()
             + onDestroyView()
             + onItemClick()
             - setList()
         }
       }
     }
    }


    namespace com.pis.buy2gether {
     namespace usecases.home {
       namespace favoriteList {
         class com.pis.buy2gether.usecases.home.favoriteList.FavoriteListAdapter {
             - groupChecked : LinkedHashMap<String, Boolean>
             - groupImage : LinkedHashMap<String, Bitmap>
             - groups : LinkedHashMap<String, String>
             - mInflater : LayoutInflater
             + addGroup()
             + getItemCount()
             + onBindViewHolder()
             + onCreateViewHolder()
             + removeGroup()
             ~ FavoriteListAdapter()
             ~ getItem()
             ~ isChecked()
             ~ setClickListener()
         }
       }
     }
    }




    namespace com.pis.buy2gether {
     namespace usecases.home {
       namespace favoriteList {
         class com.pis.buy2gether.usecases.home.favoriteList.FavoriteListAdapter.ViewHolder {
             ~ checked : RadioButton
             ~ imageView : ImageView
             ~ myTextView : TextView
             + onClick()
             ~ ViewHolder()
         }
       }
     }
    }


    namespace com.pis.buy2gether {
     namespace usecases.home {
       namespace favoriteList {
         class com.pis.buy2gether.usecases.home.favoriteList.FavoriteViewModel {
             + FavoriteViewModel()
             + delete()
             + getFavorite()
             + getGroup()
             + getUser()
         }
       }
     }
    }

    namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              class com.pis.buy2gether.usecases.home.user.friends.FriendsFragment {
                  + onClick()
                  + onCreateView()
                  + onDestroyView()
                  + onItemClick()
                  + sendRequest()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              class com.pis.buy2gether.usecases.home.user.friends.FriendsListAdapter {
                  ~ row_idx : int
                  - idFriend : LinkedHashMap<String, String>
                  - mInflater : LayoutInflater
                  - pfpFriend : LinkedHashMap<String, String>
                  - usernameFriend : LinkedHashMap<String, String>
                  + addFriend()
                  + getItemCount()
                  + onBindViewHolder()
                  + onCreateViewHolder()
                  + setUserPfp()
                  ~ FriendsListAdapter()
                  ~ getItem()
                  ~ setClickListener()
              }
            }
          }
        }
      }




      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              class com.pis.buy2gether.usecases.home.user.friends.FriendsListAdapter.ViewHolder {
                  ~ myTextView : TextView
                  ~ pfp : ShapeableImageView
                  ~ selectButton : RadioButton
                  + onClick()
                  ~ ViewHolder()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              class com.pis.buy2gether.usecases.home.user.friends.FriendsViewModel {
                  ~ searchView : SearchView
                  - context : Context
                  - list : ArrayList<Item>
                  - recyclerView : RecyclerView
                  + deleteFriend()
                  + getFriends()
                  + getUserID()
                  + getUserName()
                  + getUsers()
                  + queryTextChange()
                  + queryTextSubmit()
                  + sendRequest()
                  + sendRequest()
                  + setList()
                  + setListUsers()
                  + setup()
                  ~ FriendsViewModel()
                  - hideSearch()
                  - setUserPfp()
                  - setupUserInfo()
                  - showSearch()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              class com.pis.buy2gether.usecases.home.user.friends.UsersListAdapter {
                  ~ row_idx : int
                  - allUsers : LinkedHashMap<String, String>
                  - mInflater : LayoutInflater
                  - pfp : LinkedHashMap<String, String>
                  - user : LinkedHashMap<String, String>
                  - users : ArrayList<String>
                  + addUser()
                  + getFilter()
                  + getItemCount()
                  + onBindViewHolder()
                  + onCreateViewHolder()
                  + setUserPfp()
                  ~ UsersListAdapter()
                  ~ getItem()
                  ~ getList()
                  ~ setClickListener()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              interface com.pis.buy2gether.usecases.home.user.friends.UsersListAdapter.ItemClickListener {
                  {abstract} + onClick()
                  {abstract} + sendRequest()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace friends {
              class com.pis.buy2gether.usecases.home.user.friends.UsersListAdapter.ViewHolder {
                  ~ myTextView : TextView
                  ~ pfp : ShapeableImageView
                  ~ selectButton : RadioButton
                  + onClick()
                  ~ ViewHolder()
              }
            }
          }
        }
      }

    namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace address {
              class com.pis.buy2gether.usecases.home.user.address.AddressFragment {
                  ~ btn_add : Button
                  ~ btn_cancel : ImageButton
                  ~ btn_return : ImageButton
                  ~ btn_save : ImageButton
                  ~ popup_address : EditText
                  ~ popup_name : EditText
                  ~ popup_num : TextView
                  ~ popup_phone : EditText
                  ~ popup_postalcode : EditText
                  - list : ArrayList<Item>
                  - recyclerView : RecyclerView
                  + onClick()
                  + onCreateView()
                  + onDeleteClick()
                  + onDestroyView()
                  + onEditClick()
                  - addAddress()
                  - deleteWarning()
                  - editAddress()
                  - saveAddress()
                  - setAdapter()
                  - setList()
                  - setupAddressPopup()
                  - setupEditAddressPopup()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace address {
              class com.pis.buy2gether.usecases.home.user.address.AddressListAdapter {
                  - mData : List<Map>
                  - mInflater : LayoutInflater
                  + getItemCount()
                  + onBindViewHolder()
                  + onCreateViewHolder()
                  + swipe()
                  ~ AddressListAdapter()
                  ~ setClickListener()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace address {
              interface com.pis.buy2gether.usecases.home.user.address.AddressListAdapter.ItemClickListener {
                  {abstract} + onClick()
                  {abstract} + onDeleteClick()
                  {abstract} + onEditClick()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace address {
              class com.pis.buy2gether.usecases.home.user.address.AddressListAdapter.ViewHolder {
                  ~ address : TextView
                  ~ btn_delete : ImageButton
                  ~ btn_edit : ImageButton
                  ~ name_address : TextView
                  ~ num_address : TextView
                  ~ postal_code : TextView
                  ~ tel : TextView
                  + onClick()
                  ~ ViewHolder()
              }
            }
          }
        }
      }


      namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            namespace address {
              class com.pis.buy2gether.usecases.home.user.address.AddressViewModel {
                  + addressInfo()
                  + getAddresses()
                  ~ deleteAddressDB()
                  ~ saveAddressDB()
                  - getUser()
              }
            }
          }
        }
      }

    namespace com.pis.buy2gether {
        namespace usecases.home {
          namespace user {
            class com.pis.buy2gether.usecases.home.user.UserFragment {
                + onClick()
                + onCreateView()
                + onDestroyView()
                - setOnClickListeners()
            }
          }
        }
      }


  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        class com.pis.buy2gether.usecases.home.user.UserViewModel {
            ~ description : TextView
            ~ img_pfp : ShapeableImageView
            ~ username : TextView
            - context : Context
            + setup()
            ~ UserViewModel()
            - setUserPfp()
            - setupUserInfo()
        }
      }
    }
  }

    namespace com.pis.buy2gether {
     namespace usecases.onboarding.sign_in {
       class com.pis.buy2gether.usecases.onboarding.sign_in.RegisterActivity {
           - guest : Button
           - log : Button
           - pswEditText : TextInputEditText
           - sign : ImageButton
           - userEditText : TextInputEditText
           - usernameEditText : TextInputEditText
           # onCreate()
           - animateBackground()
           - setup()
       }
     }
    }


    namespace com.pis.buy2gether {
     namespace usecases.onboarding.sign_in {
       class com.pis.buy2gether.usecases.onboarding.sign_in.RegisterViewModel {
           - context : Context
           + saveUserInfo()
           + shakeError()
           ~ RegisterViewModel()
           ~ showAlert()
           ~ showHome()
       }
     }
    }

    namespace com.pis.buy2gether {
     namespace usecases.onboarding.log_in {
       class com.pis.buy2gether.usecases.onboarding.log_in.LoginActivity {
           - GOOGLE_SIGN_IN : int
           - forgotPassword : TextView
           - google_signin : ImageButton
           - guest : Button
           - image : ImageView
           - log : ImageButton
           - name : TextView
           - pswEditText : TextInputEditText
           - sign : Button
           - userEditText : TextInputEditText
           # onActivityResult()
           # onCreate()
           - animateBackground()
           - session()
           - setup()
           - showHome()
       }
     }
    }


    namespace com.pis.buy2gether {
     namespace usecases.onboarding.log_in {
       class com.pis.buy2gether.usecases.onboarding.log_in.LoginViewModel {
           - context : Context
           + saveUserInfo()
           + shakeError()
           ~ LoginViewModel()
           ~ getSession()
           ~ showAlert()
       }
     }
    }


  namespace com.pis.buy2gether {
      namespace usecases.home {
        namespace home {
          class com.pis.buy2gether.usecases.home.home.HomeFragment {
              - categories : Category[]
              - cloud_upload : Button
              - search_bar : EditText
              - tabLayout_categoria : TabLayout
              - viewPager_categoria : ViewPager
              + onCreateView()
              + onDestroyView()
          }
        }
      }
  }

  namespace com.pis.buy2gether {
      namespace usecases.launch {
        class com.pis.buy2gether.usecases.launch.SplashScreenActivity {
            {static} + login : boolean
            {static} - SPLASH_TIME_OUT : int
            - bottomAnim : Animation
            - image : ImageView
            - name : TextView
            - topAnim : Animation
            # onCreate()
            - test()
        }
      }
  }

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace settings {
          class com.pis.buy2gether.usecases.home.user.settings.CheckImageActivity {
              # onCreate()
              - check_Userimage()
          }
        }
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace settings {
          class com.pis.buy2gether.usecases.home.user.settings.SettingsFragment {
              ~ btn_cancel_avatar_dialog : Button
              ~ btn_cancel_changepsw_dialog : ImageButton
              ~ btn_cancel_check_img : ImageButton
              ~ btn_change_image : Button
              ~ btn_check_image : Button
              ~ btn_edit_pfp : ShapeableImageView
              ~ btn_save_change_psw : ImageButton
              ~ confirm_psw : EditText
              ~ img_check_avatar : ImageView
              ~ new_psw : EditText
              ~ userCity : EditText
              ~ userName : EditText
              - GALLERY_IMAGE_CODE : int
              - TAKE_IMAGE_CODE : int
              + onActivityResult()
              + onClick()
              + onCreateView()
              + onDestroyView()
              + showFailureAlert()
              + showSuccessAlert()
              ~ saveUserImageDB()
              - change_UserPassword()
              - change_Usercity()
              - change_Userimage()
              - change_Username()
              - check_Userimage()
              - getDownloadURL()
              - setUserPfp()
              - setupAvatarConfigurationPopup()
              - setupChangePswPopup()
              - setupCheckImagePopup()
              - showCheckImage()
              - showMediaDialog()
              - sign_out()
              - update_UserCity()
              - update_Username()
          }
        }
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace settings {
          class com.pis.buy2gether.usecases.home.user.settings.SettingsViewModel {
              - context : Context
              + SettingsViewModel()
              + clearSession()
              ~ change_UserCity()
              ~ change_Username()
              ~ update_UserInformation()
              - getUser()
          }
        }
      }
    }
  }

  usecases.launch -[hidden]-> usecases.onboarding.log_in
  usecases.onboarding.log_in -[hidden]-> usecases.onboarding.sign_in
  com.pis.buy2gether.usecases.home.user.settings.SettingsFragment o-- com.pis.buy2gether.usecases.home.user.settings.SettingsViewModel : viewModel
  com.pis.buy2gether.usecases.home.user.UserViewModel -[hidden]-> com.pis.buy2gether.usecases.home.user.UserFragment
  com.pis.buy2gether.usecases.home.user.settings.SettingsViewModel -[hidden]-> com.pis.buy2gether.usecases.home.user.settings.CheckImageActivity

right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
