@startuml

title __GRUP's Class Diagram__\n

  namespace com.pis.buy2gether {
    namespace model.domain.pojo {
      namespace Grup {
        enum Category {
          ELECTRONICA
          HOGAR
          JUGUETES
          MODA
          MUEBLES
          OTROS
          ROPA
          SALUD
          TECNOLOGIA
          VESTIDO
          ZAPATOS
        }
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace model.domain.pojo {
      namespace Grup {
        class com.pis.buy2gether.model.domain.pojo.Grup.Grup {
            - date : String
            - description : String
            - id : String
            - image : String
            - membersIds : List<String>
            - name : String
            - owner : String
            - price : float
            - proces : int
            - visibility : int
            + Grup()
            + addMember()
            + getCat()
            + getDate()
            + getDescription()
            + getId()
            + getImage()
            + getMembersIds()
            + getName()
            + getOwner()
            + getPrice()
            + getProces()
            + getVisibility()
            + setCat()
            + setDate()
            + setDescription()
            + setId()
            + setImage()
            + setMembersIds()
            + setName()
            + setOwner()
            + setPrice()
            + setProces()
            + setVisibility()
        }
      }
    }
  }
  

  com.pis.buy2gether.model.domain.pojo.Grup.Grup o-- com.pis.buy2gether.model.domain.pojo.Grup.Category : cat


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
