@startuml

title __POJO's Class Diagram__\n

  namespace com.pis.buy2gether {
    namespace model.domain.pojo {
      class com.pis.buy2gether.model.domain.pojo.Busqueda {
          - data : Date
          - searchContent : String
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace model.domain.pojo {
      class com.pis.buy2gether.model.domain.pojo.Comanda {
          - comandaID : String
          - data : String
          - grupID : String
          - stars : int
          - status : int
          - userID : String
      }
    }
  }

   namespace com.pis.buy2gether {
      namespace model.domain.pojo {
        namespace Grup {
          enum model.domain.pojo.Grup.Category {
            ELECTRONICA
            HOGAR
            JUGUETES
            MODA
            MUEBLES
            OTROS
            ROPA
            SALUD
            TECNOLOGIA
            VESTIDO
            ZAPATOS
          }
        }
      }
    }


    namespace com.pis.buy2gether {
      namespace model.domain.pojo {
        namespace Grup {
          class com.pis.buy2gether.model.domain.pojo.Grup.Grup {
              - date : String
              - description : String
              - id : String
              - image : String
              - membersIds : List<String>
              - name : String
              - owner : String
              - price : float
              - proces : int
              - visibility : int
          }
        }
      }
    }


    com.pis.buy2gether.model.domain.pojo.Grup.Grup o-- model.domain.pojo.Grup.Category : cat


  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
