@startuml

title __PESTANYES_FRAGMENTS's Class Diagram__\n

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace comanda {
          namespace pestanyes_fragments {
            class com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsFragment {
                - recyclerView : RecyclerView
                - state : int
                + TotsFragment()
                + TotsFragment()
                + onCreateView()
            }
          }
        }
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace comanda {
          namespace pestanyes_fragments {
            class com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter {
                - act : Activity
                - mData : ArrayList<Grup>
                + TotsListAdapter()
                + TotsListAdapter()
                + getItemCount()
                + onBindViewHolder()
                + onCreateViewHolder()
                + updateList()
            }
          }
        }
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace comanda {
          namespace pestanyes_fragments {
            class com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter.ViewHolder {
                ~ product_click : AppCompatImageButton
                ~ product_id : String
                ~ product_name : TextView
                ~ product_price : TextView
                ~ product_proces : TextView
                + ViewHolder()
                + getId()
                + setId()
                + setName()
                + setPrice()
                + setProces()
            }
          }
        }
      }
    }
  }
  

  namespace com.pis.buy2gether {
    namespace usecases.home {
      namespace user {
        namespace comanda {
          namespace pestanyes_fragments {
            class com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsViewModel {
                - grupList : MutableLiveData<ArrayList<Grup>>
                - state : int
                + TotsViewModel()
                + getGrupList()
                - init()
                - populateList()
                - test()
            }
          }
        }
      }
    }
  }
  

  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsFragment -up-|> androidx.fragment.app.Fragment
  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsFragment o-- com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter : adapter
  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsFragment o-- com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsViewModel : viewModel
  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter +-down- com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter.ViewHolder
  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsListAdapter.ViewHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder
  com.pis.buy2gether.usecases.home.user.comanda.pestanyes_fragments.TotsViewModel -up-|> androidx.lifecycle.ViewModel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
